version: '3.3'
services:
    db:
        image: mysql
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
    php:
        build: ./docker/php-fpm
        ports:
            - "9000:9001"
        environment:
            APP_ENV: prod
        volumes:
            - ./back:/var/www/back
            - ./logs/back:/var/www/back/var/log:cached
        links:
            - db
        extra_hosts:
            - "docker.host:127.0.0.1"
        depends_on:
            - db
    nginx:
        build: ./docker/nginx
        ports:
            - "80:80"
            - "8080:8080"
        environment:
            APP_ENV: prod
        links:
            - php
        volumes:
            - ./logs/nginx:/var/log/nginx:cached
            - ./back:/var/www/back
            - ./front:/var/www/front
    node:
        build: ./docker/node
        ports:
            - "4200:4200"
        volumes:
            - ./front:/var/www/front
            - /var/www/front/node_modules/


